apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediatordeployment
  name: mediatordeployment
  namespace: mediator
spec:
  selector:
    matchLabels:
      app: mediatordeployment
  template:
    metadata:
      labels:
        app: mediatordeployment
    spec:
      containers:
      - env:
        - name: MEDIATOR_AGENT_HTTP_ADMIN_PORT
          value: "3001"
        - name: MEDIATOR_AGENT_HTTP_IN_PORT
          value: "3000"
        - name: MEDIATOR_AGENT_LABEL
          value: "ODS_Mediator"
        - name: MEDIATOR_ENDPOINT_URL
          value: "ws.dev.mediator.candy.di.gov.on.ca"
        command:
          - bash
          - -c
          - $(echo aca-py start
            --open-mediation
            --label ODS_Mediator
            --endpoint ${MEDIATOR_ENDPOINT_URL}
            --inbound-transport http 0.0.0.0 ${MEDIATOR_AGENT_HTTP_IN_PORT}
            --outbound-transport http
            --no-ledger
            --admin 0.0.0.0 ${MEDIATOR_AGENT_HTTP_ADMIN_PORT}
            --admin-insecure-mode
            --debug-connections
            --connections-invite
            --invite-multi-use
            --auto-accept-invites
            --auto-accept-requests
            --auto-ping-connection
            --enable-undelivered-queue);
        image: image-registry.openshift-image-registry.svc:5000/candi-0000-dev/ods-candy@sha256:0a0830c2b0075e805eb73639dc9483ac8b3cde1bd8dd0f8e17e5155aecbac376
        imagePullPolicy: Always
        name: mediatordeployment
        ports:
        - containerPort: 3001
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 60m
            memory: 512Mi
          requests:
            cpu: 30m
            memory: 128Mi
      hostname: mediator
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediatorservice
  name: mediatorservice
  namespace: mediator
spec:
  ports:
  - name: httpinbound
    port: 3000
    protocol: TCP
  - name: httpadmin
    port: 3001
    protocol: TCP
  selector:
    app: mediatorservice